version: '3'

services:

  ai_ml:
    build:
      context: .
      dockerfile: ./dockerfiles/ai_ml/Dockerfile
    volumes:
      - . :/home/jovyan/work
    env_file:
      - ./dockerfiles/ai_ml/.env
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    logging:
        driver: "none"

  hbase:
    image: pierrezemb/hbase-docker:standalone-1.3.1
    links:
      - zookeeper
    logging:
      driver: "none"
    ports:
      - "16010:16010"
    expose:
      - "8080"
      - "9090"
      - "16000"
      - "16010"
      - "16020"
      - "16030"
    command: ["/wait-for-it.sh", "zookeeper:2181", "-t", "10", "--", "/usr/bin/supervisord"]