version: '3.0'

services:

  registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    ports:
      - 1111:5000
    volumes:
      - docker-registry-data:/var/lib/registry

volumes:
  docker-registry-data: {}
