version: "3"

services:
  web: &basePy
    build:
      context: .
      dockerfile: ./dockerfiles/py/Dockerfile
    volumes:
      - ./main:/main
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    env_file:
      - ./.envs/.pyenvs
    depends_on:
      - node_0
      - node_1
    links:
      - node_0
      - node_1
    restart: unless-stopped
    command: sh /bootWeb.sh

  jupyter:
    <<: *basePy
    ports:
      - "8888:8888"
    command: sh /jupyter_run.sh
    restart: unless-stopped

  node_0:
    image: cassandra:2.2.0
    restart: unless-stopped
    ports:
      - "10042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=Mycluster
      - CASSANDRA_SEEDS=node_0, node_1
      - CASSANDRA_LISTEN_ADDRESS=node_0
    links:
      - node_1

  node_1:
    image: cassandra:2.2.0
    restart: unless-stopped
    ports:
      - "11042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=Mycluster
      - CASSANDRA_SEEDS=node_0, node_1
      - CASSANDRA_LISTEN_ADDRESS=node_1

  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_files:
  uploaded_files:
